
name: pnet
gops: 0.000089

model: $(home)/pnet.prototxt
weight: $(home)/pnet.caffemodel
int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

fp32_compile_options:
  bmnetc
  --model $(model)
  --weight $(weight)
  --shapes [1,3,12,12]
  --target BM1684X
  --opt 1
  --cmp 1

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weights $(weight)
    --test_iterations 10
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd='use_fake_data_to_test;cali_extra_param=--target=BM1684X'
    --cali_iterations 20
    --input_shapes=[1,3,12,12]

bmnetu_options:
  --opt=2
  --cmp=True
  --target BM1684X
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

build_env:
  - BMCOMPILER_EXPORT_GRAPH=1
